#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Xam.RecyclerViewAnim.Resource", IsApplication=true)]

namespace Xam.RecyclerViewAnim
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f050000
			public const int item_fall_down = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int item_slide_from_bottom = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int item_slide_from_left = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int layout_fall_down = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int layout_slide_from_bottom = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int layout_slide_from_left = 2131034117;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010009
			public const int cardBackgroundColor = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public const int cardCornerRadius = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int cardElevation = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int cardMaxElevation = 2130771980;
			
			// aapt resource value: 0x7f01000e
			public const int cardPreventCornerOverlap = 2130771982;
			
			// aapt resource value: 0x7f01000d
			public const int cardUseCompatPadding = 2130771981;
			
			// aapt resource value: 0x7f01000f
			public const int contentPadding = 2130771983;
			
			// aapt resource value: 0x7f010013
			public const int contentPaddingBottom = 2130771987;
			
			// aapt resource value: 0x7f010010
			public const int contentPaddingLeft = 2130771984;
			
			// aapt resource value: 0x7f010011
			public const int contentPaddingRight = 2130771985;
			
			// aapt resource value: 0x7f010012
			public const int contentPaddingTop = 2130771986;
			
			// aapt resource value: 0x7f010004
			public const int fastScrollEnabled = 2130771972;
			
			// aapt resource value: 0x7f010007
			public const int fastScrollHorizontalThumbDrawable = 2130771975;
			
			// aapt resource value: 0x7f010008
			public const int fastScrollHorizontalTrackDrawable = 2130771976;
			
			// aapt resource value: 0x7f010005
			public const int fastScrollVerticalThumbDrawable = 2130771973;
			
			// aapt resource value: 0x7f010006
			public const int fastScrollVerticalTrackDrawable = 2130771974;
			
			// aapt resource value: 0x7f01001b
			public const int font = 2130771995;
			
			// aapt resource value: 0x7f010014
			public const int fontProviderAuthority = 2130771988;
			
			// aapt resource value: 0x7f010017
			public const int fontProviderCerts = 2130771991;
			
			// aapt resource value: 0x7f010018
			public const int fontProviderFetchStrategy = 2130771992;
			
			// aapt resource value: 0x7f010019
			public const int fontProviderFetchTimeout = 2130771993;
			
			// aapt resource value: 0x7f010015
			public const int fontProviderPackage = 2130771989;
			
			// aapt resource value: 0x7f010016
			public const int fontProviderQuery = 2130771990;
			
			// aapt resource value: 0x7f01001a
			public const int fontStyle = 2130771994;
			
			// aapt resource value: 0x7f01001c
			public const int fontWeight = 2130771996;
			
			// aapt resource value: 0x7f010000
			public const int layoutManager = 2130771968;
			
			// aapt resource value: 0x7f010002
			public const int reverseLayout = 2130771970;
			
			// aapt resource value: 0x7f010001
			public const int spanCount = 2130771969;
			
			// aapt resource value: 0x7f010003
			public const int stackFromEnd = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7f0b0000
			public const int abc_action_bar_embed_tabs = 2131427328;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f090000
			public const int cardview_dark_background = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int cardview_light_background = 2131296257;
			
			// aapt resource value: 0x7f090002
			public const int cardview_shadow_end_color = 2131296258;
			
			// aapt resource value: 0x7f090003
			public const int cardview_shadow_start_color = 2131296259;
			
			// aapt resource value: 0x7f090004
			public const int notification_action_color_filter = 2131296260;
			
			// aapt resource value: 0x7f090005
			public const int notification_icon_bg_color = 2131296261;
			
			// aapt resource value: 0x7f090006
			public const int ripple_material_light = 2131296262;
			
			// aapt resource value: 0x7f090007
			public const int secondary_text_default_material_light = 2131296263;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060006
			public const int cardview_compat_inset_shadow = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int cardview_default_elevation = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int cardview_default_radius = 2131099656;
			
			// aapt resource value: 0x7f06000d
			public const int compat_button_inset_horizontal_material = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int compat_button_inset_vertical_material = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int compat_button_padding_horizontal_material = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int compat_button_padding_vertical_material = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int compat_control_corner_material = 2131099665;
			
			// aapt resource value: 0x7f060000
			public const int fastscroll_default_thickness = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int fastscroll_margin = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int fastscroll_minimum_range = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int item_touch_helper_max_drag_scroll_per_frame = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int item_touch_helper_swipe_escape_max_velocity = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int item_touch_helper_swipe_escape_velocity = 2131099653;
			
			// aapt resource value: 0x7f060012
			public const int notification_action_icon_size = 2131099666;
			
			// aapt resource value: 0x7f060013
			public const int notification_action_text_size = 2131099667;
			
			// aapt resource value: 0x7f060014
			public const int notification_big_circle_margin = 2131099668;
			
			// aapt resource value: 0x7f06000a
			public const int notification_content_margin_start = 2131099658;
			
			// aapt resource value: 0x7f060015
			public const int notification_large_icon_height = 2131099669;
			
			// aapt resource value: 0x7f060016
			public const int notification_large_icon_width = 2131099670;
			
			// aapt resource value: 0x7f06000b
			public const int notification_main_column_padding_top = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int notification_media_narrow_margin = 2131099660;
			
			// aapt resource value: 0x7f060017
			public const int notification_right_icon_size = 2131099671;
			
			// aapt resource value: 0x7f060009
			public const int notification_right_side_padding_top = 2131099657;
			
			// aapt resource value: 0x7f060018
			public const int notification_small_icon_background_padding = 2131099672;
			
			// aapt resource value: 0x7f060019
			public const int notification_small_icon_size_as_large = 2131099673;
			
			// aapt resource value: 0x7f06001a
			public const int notification_subtext_size = 2131099674;
			
			// aapt resource value: 0x7f06001b
			public const int notification_top_pad = 2131099675;
			
			// aapt resource value: 0x7f06001c
			public const int notification_top_pad_large_text = 2131099676;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int notification_action_background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int notification_bg = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int notification_bg_low = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int notification_bg_low_normal = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int notification_bg_low_pressed = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int notification_bg_normal = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int notification_bg_normal_pressed = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int notification_icon_background = 2130837511;
			
			// aapt resource value: 0x7f02000a
			public const int notification_template_icon_bg = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int notification_template_icon_low_bg = 2130837515;
			
			// aapt resource value: 0x7f020008
			public const int notification_tile_bg = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int notify_panel_notification_icon_bg = 2130837513;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070010
			public const int action_container = 2131165200;
			
			// aapt resource value: 0x7f07001c
			public const int action_divider = 2131165212;
			
			// aapt resource value: 0x7f070011
			public const int action_image = 2131165201;
			
			// aapt resource value: 0x7f070012
			public const int action_text = 2131165202;
			
			// aapt resource value: 0x7f07001d
			public const int actions = 2131165213;
			
			// aapt resource value: 0x7f070006
			public const int async = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int blocking = 2131165191;
			
			// aapt resource value: 0x7f07000d
			public const int btnFallDown = 2131165197;
			
			// aapt resource value: 0x7f07000f
			public const int btnFromLeft = 2131165199;
			
			// aapt resource value: 0x7f07000e
			public const int btnSlideBottom = 2131165198;
			
			// aapt resource value: 0x7f07001b
			public const int chronometer = 2131165211;
			
			// aapt resource value: 0x7f070008
			public const int forever = 2131165192;
			
			// aapt resource value: 0x7f070014
			public const int icon = 2131165204;
			
			// aapt resource value: 0x7f07001e
			public const int icon_group = 2131165214;
			
			// aapt resource value: 0x7f070017
			public const int info = 2131165207;
			
			// aapt resource value: 0x7f070009
			public const int italic = 2131165193;
			
			// aapt resource value: 0x7f070000
			public const int item_touch_helper_previous_elevation = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int line1 = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int line3 = 2131165186;
			
			// aapt resource value: 0x7f07000a
			public const int normal = 2131165194;
			
			// aapt resource value: 0x7f070019
			public const int notification_background = 2131165209;
			
			// aapt resource value: 0x7f070015
			public const int notification_main_column = 2131165205;
			
			// aapt resource value: 0x7f070013
			public const int notification_main_column_container = 2131165203;
			
			// aapt resource value: 0x7f07000c
			public const int recyclerView = 2131165196;
			
			// aapt resource value: 0x7f070018
			public const int right_icon = 2131165208;
			
			// aapt resource value: 0x7f070016
			public const int right_side = 2131165206;
			
			// aapt resource value: 0x7f070003
			public const int text = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int text2 = 2131165188;
			
			// aapt resource value: 0x7f07000b
			public const int textView = 2131165195;
			
			// aapt resource value: 0x7f07001a
			public const int time = 2131165210;
			
			// aapt resource value: 0x7f070005
			public const int title = 2131165189;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f0c0001
			public const int anim_duration_medium = 2131492865;
			
			// aapt resource value: 0x7f0c0000
			public const int status_bar_notification_info_maxnum = 2131492864;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int ListItem = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int Main = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int notification_action = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int notification_action_tombstone = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int notification_template_custom_big = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int notification_template_icon_group = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int notification_template_part_chronometer = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int notification_template_part_time = 2130968583;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f0a0002
			public const int app_name = 2131361794;
			
			// aapt resource value: 0x7f0a0001
			public const int hello = 2131361793;
			
			// aapt resource value: 0x7f0a0000
			public const int status_bar_notification_info_overflow = 2131361792;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080001
			public const int Base_CardView = 2131230721;
			
			// aapt resource value: 0x7f080000
			public const int CardView = 2131230720;
			
			// aapt resource value: 0x7f080002
			public const int CardView_Dark = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int CardView_Light = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int TextAppearance_Compat_Notification = 2131230724;
			
			// aapt resource value: 0x7f080005
			public const int TextAppearance_Compat_Notification_Info = 2131230725;
			
			// aapt resource value: 0x7f08000a
			public const int TextAppearance_Compat_Notification_Line2 = 2131230730;
			
			// aapt resource value: 0x7f080006
			public const int TextAppearance_Compat_Notification_Time = 2131230726;
			
			// aapt resource value: 0x7f080007
			public const int TextAppearance_Compat_Notification_Title = 2131230727;
			
			// aapt resource value: 0x7f080008
			public const int Widget_Compat_NotificationActionContainer = 2131230728;
			
			// aapt resource value: 0x7f080009
			public const int Widget_Compat_NotificationActionText = 2131230729;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CardView = new int[] {
					16843071,
					16843072,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987};
			
			// aapt resource value: 1
			public const int CardView_android_minHeight = 1;
			
			// aapt resource value: 0
			public const int CardView_android_minWidth = 0;
			
			// aapt resource value: 2
			public const int CardView_cardBackgroundColor = 2;
			
			// aapt resource value: 3
			public const int CardView_cardCornerRadius = 3;
			
			// aapt resource value: 4
			public const int CardView_cardElevation = 4;
			
			// aapt resource value: 5
			public const int CardView_cardMaxElevation = 5;
			
			// aapt resource value: 7
			public const int CardView_cardPreventCornerOverlap = 7;
			
			// aapt resource value: 6
			public const int CardView_cardUseCompatPadding = 6;
			
			// aapt resource value: 8
			public const int CardView_contentPadding = 8;
			
			// aapt resource value: 12
			public const int CardView_contentPaddingBottom = 12;
			
			// aapt resource value: 9
			public const int CardView_contentPaddingLeft = 9;
			
			// aapt resource value: 10
			public const int CardView_contentPaddingRight = 10;
			
			// aapt resource value: 11
			public const int CardView_contentPaddingTop = 11;
			
			public static int[] FontFamily = new int[] {
					2130771988,
					2130771989,
					2130771990,
					2130771991,
					2130771992,
					2130771993};
			
			// aapt resource value: 0
			public const int FontFamily_fontProviderAuthority = 0;
			
			// aapt resource value: 3
			public const int FontFamily_fontProviderCerts = 3;
			
			// aapt resource value: 4
			public const int FontFamily_fontProviderFetchStrategy = 4;
			
			// aapt resource value: 5
			public const int FontFamily_fontProviderFetchTimeout = 5;
			
			// aapt resource value: 1
			public const int FontFamily_fontProviderPackage = 1;
			
			// aapt resource value: 2
			public const int FontFamily_fontProviderQuery = 2;
			
			public static int[] FontFamilyFont = new int[] {
					2130771994,
					2130771995,
					2130771996};
			
			// aapt resource value: 1
			public const int FontFamilyFont_font = 1;
			
			// aapt resource value: 0
			public const int FontFamilyFont_fontStyle = 0;
			
			// aapt resource value: 2
			public const int FontFamilyFont_fontWeight = 2;
			
			public static int[] RecyclerView = new int[] {
					16842948,
					16842993,
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976};
			
			// aapt resource value: 1
			public const int RecyclerView_android_descendantFocusability = 1;
			
			// aapt resource value: 0
			public const int RecyclerView_android_orientation = 0;
			
			// aapt resource value: 6
			public const int RecyclerView_fastScrollEnabled = 6;
			
			// aapt resource value: 9
			public const int RecyclerView_fastScrollHorizontalThumbDrawable = 9;
			
			// aapt resource value: 10
			public const int RecyclerView_fastScrollHorizontalTrackDrawable = 10;
			
			// aapt resource value: 7
			public const int RecyclerView_fastScrollVerticalThumbDrawable = 7;
			
			// aapt resource value: 8
			public const int RecyclerView_fastScrollVerticalTrackDrawable = 8;
			
			// aapt resource value: 2
			public const int RecyclerView_layoutManager = 2;
			
			// aapt resource value: 4
			public const int RecyclerView_reverseLayout = 4;
			
			// aapt resource value: 3
			public const int RecyclerView_spanCount = 3;
			
			// aapt resource value: 5
			public const int RecyclerView_stackFromEnd = 5;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
